networks:
  fit_mate:
    external: true

services:
  postgresql-auth:
    image: postgres:latest
    container_name: postgresql-auth
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cksrb0402
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fit_mate

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER_NAME: auth-service
    container_name: auth-service
    restart: on-failure
    depends_on:
      - postgresql-auth
    ports:
      - "8084:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fit_mate
