server:
  port: 8080

spring:
  container-name: ${CONTAINER_NAME}
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgresql-auth:5432/postgres
    username: auth
    password: auth1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka-1:9092
    topic-config:
      user-create-event:
        topic-name: user-create-event
      user-delete-event:
        topic-name: user-delete-event
      user-update-event:
        topic-name: user-update-event
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.200.62.156:8761/eureka

#springdoc:
#  swagger-ui:
#    path: /api-docs

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html