server:
  port: 8080


spring:
  application:
    name: oauth

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cksrb0402
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: kafka-1:19092