server:
  port: 8080

spring:
  container-name: ${CONTAINER_NAME}
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgresql-auth:5432/postgres
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka-1:9092
    topic-config:
      user-create-event:
        topic-name: user-create-event
      user-delete-event:
        topic-name: user-delete-event
      user-update-event:
        topic-name: user-update-event
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#springdoc:
#  swagger-ui:
#    path: /api-docs

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html