server:
  port: 18080

spring:
  container-name : test

  application:
    name: oauth

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cksrb0402
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka-1:19092

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 서버 설정, 다중화 시 콤마 로 구분